apiVersion: apps/v1
kind: Deployment
metadata:
  name: rinna-generate-gpu-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rinna-generate-gpu-app
  template:
    metadata:
      labels:
        app: rinna-generate-gpu-app
    spec:
      containers:
      - name: rinna-generate-gpu-app
        image: $_CONTAINER_IMAGE:$_SERVER
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: PORT
            value: "8080"
          - name: _SERVER
            value : $_SERVER
        resources:
            limits:
                nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rinna-generate-gpu-app-service
  namespace: default
  labels:
    app: rinna-generate-gpu-app

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

  selector:
    app: rinna-generate-gpu-app